### PR TITLE
Hex binary value support

### PR DESCRIPTION
**Pull request by girishchandranc**

### CODE REVIEW

**Comment by girishchandranc** [comment]
Hi Adi, Please review!

**Comment by PopAdrian1981** [comment]
I think our test arxml file still contains values it cannot process.
e.g. :

> invalid literal for int() with base 8: ''

> autosarfactory-0.2.1-py3.8.egg\autosarfactory\datatype_utils.py(13)get_int_value()
>      11         else:
>      12             # octal value
> ---> 13             return int(text[2:], 8)
>      14     else:
>      15         # decimal value

**Comment by girishchandranc** [comment]
> I think our test arxml file still contains values it cannot process.
> e.g. :
> 
> > invalid literal for int() with base 8: ''
> 
> > autosarfactory-0.2.1-py3.8.egg\autosarfactory\datatype_utils.py(13)get_int_value()
> > 11         else:
> > 12             # octal value
> > ---> 13             return int(text[2:], 8)
> > 14     else:
> > 15         # decimal value

Hi Adi, The issue is fixed and now able to open the UI with test arxml. Please re-review.

**Review by PopAdrian1981 — APPROVED** [review]
Looks good! Works with the large test file we had.
Perhaps we should establish some rules for updating the version; what do you think? (Right now the the branches will both update to the same version with different changes).

**Pull request merged**
